name: Build MihanRP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile MihanRP
        id: compiler
        uses: knryuu/pawn-compiler-action@v1
        with:
          input: gamemodes/new.pwn
          includes: pawno/include

      - name: Upload AMX
        uses: actions/upload-artifact@v4
        with:
          name: mihanrp-amx
          path: ${{ steps.compiler.outputs.compiled_file }}
